import {
  pgTable,
  index,
  pgPolicy,
  check,
  unique,
  foreignKey,
  uuid,
  text,
  boolean,
  timestamp,
  jsonb,
} from 'drizzle-orm/pg-core'
import { sql } from 'drizzle-orm'

export const skimSources = pgTable(
  'skim_sources',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    userId: text('user_id').notNull(),
    name: text('name').notNull(),
    feedUrl: text('feed_url').notNull(),
    kind: text('kind').notNull().default('rss'),
    enabled: boolean('enabled').notNull().default(true),
    lastPolledAt: timestamp('last_polled_at', { withTimezone: true, mode: 'string' }),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' }).notNull().defaultNow(),
  },
  (table) => [
    index('idx_skim_sources_user_id').using('btree', table.userId.asc().nullsLast().op('text_ops')),
    index('idx_skim_sources_user_enabled').using('btree', table.userId.asc().nullsLast().op('text_ops'), table.enabled.asc().nullsLast()),
    check('skim_sources_kind_check', sql`kind IN ('rss', 'reddit', 'hackernews', 'googlenews', 'other')`),
    unique('skim_sources_user_feed_unique').on(table.userId, table.feedUrl),
    pgPolicy('skim_sources_rls_select', { as: 'permissive', for: 'select', to: ['public'], using: sql`(user_id = (select current_setting('app.current_user_id')))` }),
    pgPolicy('skim_sources_rls_insert', { as: 'permissive', for: 'insert', to: ['public'], withCheck: sql`(user_id = (select current_setting('app.current_user_id')))` }),
    pgPolicy('skim_sources_rls_update', { as: 'permissive', for: 'update', to: ['public'], using: sql`(user_id = (select current_setting('app.current_user_id')))` }),
    pgPolicy('skim_sources_rls_delete', { as: 'permissive', for: 'delete', to: ['public'], using: sql`(user_id = (select current_setting('app.current_user_id')))` }),
  ],
)

export const skimArticles = pgTable(
  'skim_articles',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    userId: text('user_id').notNull(),
    sourceId: uuid('source_id'),
    url: text('url').notNull(),
    originalTitle: text('original_title'),
    skimTitle: text('skim_title'),
    sourceName: text('source_name'),
    theNews: text('the_news'),
    whyItMatters: text('why_it_matters'),
    ariInspiration: text('ari_inspiration'),
    suggestedModuleName: text('suggested_module_name'),
    pillar: text('pillar'),
    tags: jsonb('tags').notNull().default(sql`'[]'::jsonb`),
    publishedAt: timestamp('published_at', { withTimezone: true, mode: 'string' }),
    status: text('status').notNull().default('pending'),
    errorMessage: text('error_message'),
    isRead: boolean('is_read').notNull().default(false),
    isSaved: boolean('is_saved').notNull().default(false),
    hasBuiltModule: boolean('has_built_module').notNull().default(false),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' }).notNull().defaultNow(),
  },
  (table) => [
    index('idx_skim_articles_user_id').using('btree', table.userId.asc().nullsLast().op('text_ops')),
    index('idx_skim_articles_user_created').using(
      'btree',
      table.userId.asc().nullsLast().op('text_ops'),
      table.createdAt.desc().nullsFirst().op('timestamptz_ops'),
    ),
    index('idx_skim_articles_user_status').using('btree', table.userId.asc().nullsLast().op('text_ops'), table.status.asc().nullsLast().op('text_ops')),
    index('idx_skim_articles_user_pillar').using('btree', table.userId.asc().nullsLast().op('text_ops'), table.pillar.asc().nullsLast().op('text_ops')),
    index('idx_skim_articles_source_id').using('btree', table.sourceId.asc().nullsLast().op('uuid_ops')),
    check('skim_articles_status_check', sql`status IN ('pending', 'processing', 'ready', 'failed')`),
    check(
      'skim_articles_pillar_check',
      sql`pillar IS NULL OR pillar IN ('ai-llms', 'automation', 'productivity', 'nocode-ai', 'other')`,
    ),
    unique('skim_articles_user_url_unique').on(table.userId, table.url),
    foreignKey({
      columns: [table.sourceId],
      foreignColumns: [skimSources.id],
      name: 'skim_articles_source_id_fkey',
    }).onDelete('set null'),
    pgPolicy('skim_articles_rls_select', { as: 'permissive', for: 'select', to: ['public'], using: sql`(user_id = (select current_setting('app.current_user_id')))` }),
    pgPolicy('skim_articles_rls_insert', { as: 'permissive', for: 'insert', to: ['public'], withCheck: sql`(user_id = (select current_setting('app.current_user_id')))` }),
    pgPolicy('skim_articles_rls_update', { as: 'permissive', for: 'update', to: ['public'], using: sql`(user_id = (select current_setting('app.current_user_id')))` }),
    pgPolicy('skim_articles_rls_delete', { as: 'permissive', for: 'delete', to: ['public'], using: sql`(user_id = (select current_setting('app.current_user_id')))` }),
  ],
)
